### ISSUE TITLE
Requirement of file even when the file is provided

### ISSUE THREAD

**Issue by maanzaa** [UofLBioinformatics/seekCRIT#1]
Hello !
I am quite new to using seekCRIT. I want to check the expression of my circRNAs using RNA seq. I have given all the required arguments in the command but it keeps throwing error.  I have included the gtf file, but then the program asks me to include gtf file. The command used is:

python3 seekCRIT.py -o AC16_PEtest -t PE -fa /STORAGE/softwares/seekCRIT/genome/Homo_sapiens.GRCh38.dna.primary_assembly.fa  --genomeIndex /STORAGE/softwares/seekCRIT/hg38_index -s1 /STORAGE/softwares/seekCRIT/circrna_ac16/AC16_RNA_Doxo_1.fastq:/STORAGE/softwares/seekCRIT/circrna_ac16/AC16_RNA_Doxo_2.fastq -s2 /STORAGE/softwares/seekCRIT/circrna_ac16/AC16_RNA_1.fastq:/STORAGE/softwares/seekCRIT/circrna_ac16/AC16_RNA_2.fastq --gtf/STORAGE/softwares/seekCRIT/genome/Homo_sapiens.GRCh38.99.gtf  --threadNumber 20

The error is :
![Screenshot from 2021-04-16 21-32-00](https://user-images.githubusercontent.com/82668933/115052395-84fbb380-9efb-11eb-921c-d387c6712ec3.png)

Kindly help!

Thanks,
Manasa

**Comment by bluebear94** [comment]
It seems you forgot to put a space after `--gtf`. Since you've opened another issue where you fixed this, I'm going to close this one if you don't mind.
